apiVersion: v1
kind: Secret
metadata:
  name: notifications-secret
type: Opaque
data:
  RABBITMQ_URL: YW1xcDovL2d1ZXN0Omd1ZXN0QDQ3LjEzMC4xNTEuMjI3Lw==
  COGNITO_USER_POOL_ID: YXAtc291dGhlYXN0LTFfVVJ5cXVSMVBI
  COGNITO_REGION: YXAtc291dGhlYXN0LTE=
  NODEMAIL: a2F2aW5kYWFsdWRlbml5YUBnbWFpbC5jb20=
  APP_PASS: b3ZjdiBubHZlIGx6a3ggbWx1ZQ==
