apiVersion: v1
kind: Secret
metadata:
  name: events-service-secrets
  namespace: ticket-booking
type: Opaque
data:
  DATABASE_URL: <base64-encoded-database-url>
  RABBITMQ_URL: <base64-encoded-rabbitmq-url>
  COGNITO_USER_POOL_ID: <base64-encoded-cognito-user-pool-id>
  COGNITO_REGION: <base64-encoded-cognito-region>