apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: 859793947578.dkr.ecr.ap-southeast-1.amazonaws.com/payments:latest
          ports:
            - containerPort: 3004
          envFrom:
            - configMapRef:
                name: payments-config
            - secretRef:
                name: payments-secret
---
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  type: ClusterIP
  selector:
    app: payments
  ports:
    - port: 3004
      targetPort: 3004