apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  RABBITMQ_URL: YW1xcDovL2d1ZXN0Omd1ZXN0QDQ3LjEzMC4xNTEuMjI3Lw==
  COGNITO_USER_POOL_ID: YXAtc291dGhlYXN0LTFfVVJ5cXVSMVBI
  COGNITO_REGION: YXAtc291dGhlYXN0LTE=
  COGNITO_APP_CLIENT_ID: NWt0bzlqbzdiNW9vbTlnaGVvdnRudmM4YmU=
  COGNITO_APP_CLIENT_SECRET: aXFmc2k0am4xNXNnMnZoMTl1ZjdoYmF2aWdjYmhsdmswczNndnJkYjBpbTBhNGJxbQ==

