AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Auth service for the Ticket Booking System

Globals:
  Function:
    Timeout: 10
    MemorySize: 512
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    CodeUri: .
    Environment:
      Variables:
        #NODE_ENV: !Ref Environment

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Environment name

Resources:
  HTTPApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
          - Access-Control-Allow-Origin
        AllowOrigins:
          - http://localhost:3000     # Development
          - https://localhost:3000     # Development
        AllowCredentials: true

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/hello.default
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref HTTPApi
            PayloadFormatVersion: '2.0'
            Path: /auth/hello
            Method: get
    Metadata:
      Fn::Transform:
        Name: 'AWS::Include'
        Parameters:
          Location: commonMetadata.yaml

  SignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/signup.default
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref HTTPApi
            PayloadFormatVersion: '2.0'
            Path: /auth/signup
            Method: post
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:AdminAddUserToGroup
              Resource: arn:aws:cognito-idp:ap-southeast-1:859793947578:userpool/ap-southeast-1_URyquR1PH
    Metadata:
      Fn::Transform:
        Name: 'AWS::Include'
        Parameters:
          Location: commonMetadata.yaml

  EmailVerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/email-verification.default
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref HTTPApi
            PayloadFormatVersion: '2.0'
            Path: /auth/verify-email
            Method: post
    Metadata:
      Fn::Transform:
        Name: 'AWS::Include'
        Parameters:
          Location: commonMetadata.yaml

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/login.default
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref HTTPApi
            PayloadFormatVersion: '2.0'
            Path: /auth/login
            Method: post
    Metadata:
      Fn::Transform:
        Name: 'AWS::Include'
        Parameters:
          Location: commonMetadata.yaml


Outputs:
  HttpApiEndpoint:
    Description: "HTTP API Endpoint URL"
    Value: !Sub "https://${HTTPApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"