version: 0.2

env:
  variables:
    ECR_REPO: 859793947578.dkr.ecr.ap-southeast-1.amazonaws.com/bookings
    IMAGE_TAG: $CODEBUILD_RESOLVED_SOURCE_VERSION

phases:
  install:
    commands:
      - echo Skipping kubectl installation...

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $ECR_REPO
      - REPOSITORY_URI=$ECR_REPO
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH}

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG -f bookings/Dockerfile bookings

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - bookings/bookings-deployment.yaml
